In [1]:
import numpy as np

In [4]:
weight_vector = np.array([[1],[1],[1]])
x_vector = np.array([[3],[4],[5]])

weight_vector


array([[1],
       [1],
       [1]])

In [6]:
x_vector

array([[3],
       [4],
       [5]])

In [7]:
weight_vector.T.dot(x_vector)

array([[12]])

# pandas_series

In [8]:
from pandas import Series,DataFrame
import pandas as ps
import numpy as np

In [10]:
list_data = [1,2,3,4,5]
example_obj = Series(data = list_data)
#list는 여러 자료형을 저장할 수 있다.
example_obj

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [11]:
list_data = [1,2,3,4,5]
list_name = ["a","b","c","d","e"]
example_obj = Series(data = list_data, index = list_name)
example_obj

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [12]:
 example_obj.index


Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [13]:
 example_obj.values


array([1, 2, 3, 4, 5], dtype=int64)

In [14]:
type(example_obj.values)


numpy.ndarray